server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: aimusic
  profiles:
    active: @spring.profiles.active@
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:123456}
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=24h,expireAfterAccess=6h

# AI配置
ai:
  base-url: ${AI_BASE_URL:https://api.openai.com/v1}
  api-key: ${AI_API_KEY:your-api-key-here}
  model-name: ${AI_MODEL_NAME:gpt-4}
  timeout: ${AI_TIMEOUT:30}

# 代理配置
proxy:
  enabled: ${PROXY_ENABLED:false}
  host: ${PROXY_HOST:127.0.0.1}
  port: ${PROXY_PORT:7897}

# 应用配置
app:
  max-question-length: 500

logging:
  level:
    com.aimusic: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/aimusic.log
    max-size: 10MB
    max-history: 30

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-home-custom: true
    home-custom-path: classpath:README.md
  production: false
  basic:
    enable: false

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true